// <auto-generated />
using MVCHamburgerProjesi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MVCHamburgerProjesi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("MVCHamburgerProjesi.Data.Ekstra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("EkstraAd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Fiyat")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Ekstralar");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EkstraAd = "Ketçap",
                            Fiyat = 1m
                        },
                        new
                        {
                            Id = 2,
                            EkstraAd = "Mayonez",
                            Fiyat = 1m
                        },
                        new
                        {
                            Id = 3,
                            EkstraAd = "Acı Sos",
                            Fiyat = 2m
                        });
                });

            modelBuilder.Entity("MVCHamburgerProjesi.Data.Menu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<decimal>("Fiyat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MenuAd")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Menuler");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Fiyat = 45m,
                            MenuAd = "Whopper"
                        },
                        new
                        {
                            Id = 2,
                            Fiyat = 60m,
                            MenuAd = "Double Whopper"
                        },
                        new
                        {
                            Id = 3,
                            Fiyat = 65m,
                            MenuAd = "Double Köfteburger"
                        },
                        new
                        {
                            Id = 4,
                            Fiyat = 55m,
                            MenuAd = "Cheeseburger"
                        });
                });

            modelBuilder.Entity("MVCHamburgerProjesi.Data.Siparis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Adet")
                        .HasColumnType("int");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<string>("Boyut")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EkstraId")
                        .HasColumnType("int");

                    b.Property<string>("Ekstralar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MenuId")
                        .HasColumnType("int");

                    b.Property<decimal>("ToplamTutar")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("MenuId");

                    b.ToTable("Siparis");
                });

            modelBuilder.Entity("MVCHamburgerProjesi.Data.Siparis", b =>
                {
                    b.HasOne("MVCHamburgerProjesi.Data.Menu", "SeciliMenu")
                        .WithMany()
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SeciliMenu");
                });
#pragma warning restore 612, 618
        }
    }
}
